services:
  app:
    build: .
    ports:
      - "${FASTIFY_PORT}:3000"
    env_file: .env
    volumes:
      - ./:/app
      - ./uploads:/app/uploads 
      - /app/node_modules
      - ./data:/app/data
    command: npm run dev